{-
   Bot Server API

   This is a bot API to let bots battle

   OpenAPI Version: 3.0.0
   Bot Server API API version: 1.0.0
   Contact: szederjesiarnold@gmail.com
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : BotServer.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module BotServer.Logging
  ( module BotServer.LoggingKatip
  ) where

import BotServer.LoggingKatip

#else

module BotServer.Logging
  ( module BotServer.LoggingMonadLogger
  ) where

import BotServer.LoggingMonadLogger

#endif
